name = "qpyc"
author = "Zhenghao Yin"
repository = "https://bitbucket.univie.ac.at/scm/~yinz96/qpyc.git"
readme = "README"

requires = [
    "numpy",
    "qubib",
    "pyserial >= 3.0",
    "pyvisa >= 1.11",
    "Pyro5 >= 5.13"
]